# Numpy数组(ndarray)
## 1.ndarray特性
多维性：支持0维，1维，2维以及更高维数组

同质性：所有元素类型必须一至

高效性：基于连续内存块存储，支持向量运算


In [4]:
import numpy as np
from numpy.ma.core import count

arr = np.array(5) #创建0维ndarray数组

print(f"ndarray的维度： {arr.ndim}")

ndarray的维度： 0


In [7]:
import numpy as np

arr = np.array([1,2,3]) #创建1维ndarray数组

print(arr)

print(f"ndarray的维度： {arr.ndim}")

[1 2 3]
ndarray的维度： 1


In [13]:
arr = np.array([[1,2,3], [2,3,4]]) #创建2维ndarray数组

print(arr)

print(f"ndarray的维度： {arr.ndim}")

[[1 2 3]
 [2 3 4]]
ndarray的维度： 2


# 同质性

In [ ]:
arr=np.array([1,2,3])# cast int to string

print(arr)

print(arr.T)

## 2.ndarray的属性

 shape 数组的形状
 ndim  维度
 size  总个数
dtype  数组中元素的类型
T:转置


In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)

print(arr.ndim)

print(f"元素的个数: {arr.size}")

print(f"元素的数据类型：{arr.dtype}")

print(f"矩阵转置:{arr.T}")



(3, 3)
2
元素的个数: 9
元素的数据类型：int64
矩阵转置:[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 3.ndarray创建

In [51]:
list=[1,2,3,4]

# 基础创建方法
arr=np.array(list,dtype=np.float64)

print(arr)

#copy创建
arr1=np.copy(arr)
print(arr1)

print(type(arr))

[1. 2. 3. 4.]
[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [110]:
#预定义形状
# 全0

arr=np.zeros((2,3),dtype=int)
print(arr)
print("------------")
arr1=np.zeros(4,dtype=int)
print(arr1)

print("------------")
#全1
arr2=np.ones((3,3),dtype=int)
print(arr2)

[[0 0 0]
 [0 0 0]]
------------
[0 0 0 0]
------------
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [50]:
# full，使用指定值填充数组
arr=np.full((3,3),2)
print(arr)

print("------------")
#.._like创建指定形状的矩阵
arr1=np.zeros_like(arr1)
print(arr1)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
------------
[0. 0. 0. 0.]


In [54]:
# 等差数列
"""
param1:start
param2:end(不包含)
param3:步长
"""
arr=np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [67]:
# 等间隔数列 划分间隔
arr=np.linspace(0,10,4,dtype=int)
print(arr)

arr1=np.arange(0,101,25)
print(arr1)

[ 0  3  6 10]
[  0  25  50  75 100]


In [70]:
#对数间隔 0 1 2 3 4 5 6 7 8 9 10(0,3,6,10)
arr=np.logspace(0,10,4,base=2,dtype=int)

print(arr)

[   1   10  101 1024]


# 特殊矩阵的构造

In [78]:
# 单位矩阵：主对角线全是1，其余为0

arr=np.eye(3,4,dtype=int)

print(arr)

print("-----------")
#对角矩阵：主对角线非0，其余为0
arr=np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
-----------
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [86]:
#随机数组的生成
#生成0-1随机浮点数（均匀分布）

arr=np.random.rand(2,3)
print(arr)

print("--------------")

#生成指定范围区间的指定浮点数
np.random.uniform(3,6,(2,3))



[[0.82159686 0.11302168 0.02132071]
 [0.93690392 0.26009625 0.00991694]]
--------------


array([[5.73387825, 5.06507303, 5.80564334],
       [3.81708452, 3.54194294, 3.10725056]])

In [90]:
#生成指定范围的int
np.random.randint(2,10,(3,3))

array([[9, 5, 7],
       [8, 4, 7],
       [5, 3, 5]], dtype=int32)

In [99]:
# 生成随机数列(正态分布）
arr=np.random.randn(2,3)
print(arr)

[[-0.23289865  2.64370212  0.07631536]
 [-0.83283022 -1.44024046  0.0748146 ]]


In [109]:
#设置随机种子
np.random.seed(20)

np.random.randint(1,10,(3,3))

array([[4, 5, 7],
       [8, 3, 1],
       [7, 9, 6]], dtype=int32)

## 4. ndarry数据类型

1.**bool**
2.**int,uint**:int8,int16,int32,int64
3.**float**:float16,float32,float64
4.**complex**:


## 5.索引与切片

### 1.基本索引
### 2.行列切片
### 3.连续切片
### 4.slice
### 5.bool索引


In [119]:
#一维数组
arr=np.random.randint(1,10,10)
print(arr)

print(arr[:])
print(arr[:3])#左开右闭

print(arr[arr>5])#bool索引

[6 7 6 3 7 2 9 2 1 9]
[6 7 6 3 7 2 9 2 1 9]
[6 7 6]
[6 7 6 7 9 9]


In [128]:
arr=np.random.randint(1,10,(3,3))
print(arr)
print("----------")

print(arr[0,2])

#切片
print(arr[2,:])

#bool索引

print(arr[arr>5])

print(arr[1][arr[1]>5])

print(arr[:,2][arr[:,2]<5])


[[1 5 9]
 [7 5 7]
 [7 8 3]]
----------
9
[7 8 3]
[9 7 7 7 8]
[7 7]
[3]


## 5.ndarray的运算


In [137]:
#算数运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[9,10,11]])
#对应位置进行运算


#矩阵操作
print(a+b)
print("--------------")
print(a+3)
print("--------------")

print(a*b)#对应位置相乘，并非矩阵乘法
print("--------------")
print(a@b)#矩阵乘法

[[ 5  7  9]
 [11 13 15]
 [16 18 20]]
--------------
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------
[[ 4 10 18]
 [28 40 54]
 [63 80 99]]
--------------
[[ 45  51  57]
 [105 120 135]
 [165 189 213]]


# 6.numpy常用函数

In [154]:
#sqrt
print(np.sqrt(9))
list=np.array([1,2,3,4,5])
print(np.sqrt(list))

#指数
print(np.exp(1)) #e^1

#计算自然对数 lnx
print(np.log(2.718281828459045))

#计算三角函数
print(np.sin(np.pi/2),np.cos(0))

#计算绝对值
arr=np.array([1,-2,3,-1,-7])
print(np.abs(arr))

#计算a^b 2^10
print(np.power(2,10))

#四舍五入 2.5->2.0
print(np.round(2.58))

#检查缺失值
print(np.isnan([1, 2, np.nan]))

3.0
[1.         1.41421356 1.73205081 2.         2.23606798]
2.718281828459045
1.0
1.0 1.0
[1 2 3 1 7]
1024
3.0
[False False  True]


统计函数

In [5]:
arr=np.array([2,1,3,4,5,2])#1 2 2 3 4 5
print(arr)
# 求和
print(np.sum(arr))

#平均值
print(np.mean(arr))

#中位数
print(np.median(arr))

#计算标准差，方差
print(np.var(arr))#方差
print(np.std(arr))#标准差

#最大值 max 最小值 min

#分位数
print(np.percentile(arr,25))

#累积和，累积积
print(np.sum(arr))
print(np.cumsum(arr))#前缀和
print(np.cumprod(arr))#前缀积

[2 1 3 4 5 2]
17
2.8333333333333335
2.5
1.8055555555555556
1.3437096247164249
2.0
17
[ 2  3  6 10 15 17]
[  2   2   6  24 120 240]


比较函数


In [9]:
#是否大于
print(np.greater([1, 2, 3, 4, 5, 6], 5)) #np.less()是否小于
#是否等于，多维对应位置进行判断
print(np.equal([1, 2, 3, 4, 5, 6], 3))

#检查是否有至少有一个元素为true
print(np.any([0,0,0,0,0]))

[False False False False False  True]
[False False  True False False False]
False


排序函数

In [21]:

np.random.seed(0)
arr =np.random.randint(1,100,20)

print(arr)

print(np.sort(arr))


[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


去重函数

In [22]:
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [23]:
#调整数组形状
print(np.reshape(arr,(4,5)))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]


# 案例练习

In [32]:
"""
某城市一周最高温度
"""

data=[28,30,29,31,32,30,29]

arr=np.array(data)

print(f"该周最高温度为{arr.max()},最低温度为{arr.min()},平均温度为 %.3f"%
      arr.mean() )

print(f"温度超过30天的天数为{len(arr[arr>30])}天")
#print(np.sum(np.where(arr>30,1,0)))
#print(np.cumsum(np.where(arr[arr>30],1,0))[-1])


该周最高温度为32,最低温度为28,平均温度为 29.857
温度超过30天的天数为2天
2


In [40]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(a+b)
print(a*b)
print(a@b)
print(np.dot(a,b))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [38]:
score=np.array([85,90,78,92,88])

print("分数的平均分为%.2f,中位数为%d,标准差为%.2f"%(np.mean(score),np.median(score),np.std(score)))


分数的平均分为86.60,中位数为88,标准差为4.88


In [57]:
arr=np.random.randint(0,10,(3,4))
print(arr)

#计算每一列的最大值和每行的最小值
# for i in range(len(arr)):
#    print("第%d行的最小值为%d"%(i+1,np.min(arr[i][:])))
#
# for i in range(len(arr[0])):
#     print("第%d列的最大值为%d"%(i+1,np.max(arr[:,i])))

"""
axis=0 :按列取
axis=1 ：按行取
"""
print(f"每列的最大值{np.max(arr,axis=0)}")
print(f"每行的最小值{np.min(arr,axis=1)}")


#将所有奇数替换为-1
print(np.where(arr%2==1,-1,arr))
print("----------------")
arr[arr%2==1]=-1
print(arr)


[[3 9 7 5]
 [3 4 5 3]
 [3 7 9 9]]
每列的最大值[3 9 9 9]
每行的最小值[3 3 3]
[[-1 -1 -1 -1]
 [-1  4 -1 -1]
 [-1 -1 -1 -1]]
----------------
[[-1 -1 -1 -1]
 [-1  4 -1 -1]
 [-1 -1 -1 -1]]


In [74]:
arr=np.arange(1,13,1)
#print(arr)

arr=np.reshape(arr, (3, 4))

print(arr)

print(f"每行的和{np.sum(arr,axis=1)}")

print(f"每列的平均值{np.mean(arr,axis=0)}")

# arr1=[i for row in arr for i in row]
# print(arr1)


print(np.reshape(arr,(12)))





#计算每行的和与每列的平均值
#print(f"每行的和{}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和[10 26 42]
每列的平均值[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [82]:
#布尔索引
arr=np.random.randint(0,20,(5,5))
print(arr)

print(arr[arr>10])

arr[arr>10]=0
print(arr)

[[18 13  4  4 12]
 [17  1  5  1 19]
 [19  7  9 17  9]
 [ 0 19  4 17 16]
 [ 3 10  1  4  4]]
[18 13 12 17 19 19 17 19 17 16]
[[ 0  0  4  4  0]
 [ 0  1  5  1  0]
 [ 0  7  9  0  9]
 [ 0  0  4  0  0]
 [ 3 10  1  4  4]]


In [90]:
#某公司六个月销售额
data=np.array([120,135,110,125,130,140])

print("销售额总和%d"%np.sum(data))

print("销售额均值%d"%np.mean(data))

print("销售方差%.3f"%np.var(data))

print("最高的月份",np.argmax(data)+1)
print("最低的月份",np.argmin(data)+1)


销售额总和760
销售额均值126
销售方差97.222
最高的月份 6
最低的月份 3


In [99]:
a=[1,2,3]
b=[3,4,5]

a=np.array(a)
b=np.array(b)

print(np.concatenate([a, b]))
c = np.concatenate([a, b])
print(np.reshape(c, (2, 3)))

[1 2 3 3 4 5]
[[1 2 3]
 [3 4 5]]


In [104]:
money=np.array([20,25,22,30,28])

cost=np.array([15,18,16,22,20])

print("每天的利润:",money-cost)

profit=money-cost

print("平均利润",np.mean(profit))
print("利润标准差%.3f"%np.std(profit))

max_profit=np.max(profit)
print("利润最高的天数为：",len(profit[profit==max_profit]))

每天的利润: [5 7 6 8 8]
平均利润 6.8
利润标准差1.166
利润最高的天数为： 2
